name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        platform:
          - ubuntu
          - macos
          - windows
    name: Build and Test
    runs-on: ${{ matrix.platform }}-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Install
      run: cargo install --debug --path .
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      run: cargo clippy --verbose -- -D warnings
  tagger:
    name: Tag
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main')
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag 
        id: tag
        if: always() && needs.build.result == 'success'
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: norelease #patch, minor, major, norelease
          tag_prefix: v
